import 'package:barbershop_new/src/helpers/constants.dart';
import 'package:barbershop_new/src/helpers/screens.dart';
import 'package:barbershop_new/src/widgets/custom_app_bar.dart';
import 'package:barbershop_new/src/widgets/custom_elevated_button.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_feather_icons/flutter_feather_icons.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:octo_image/octo_image.dart';

part 'screens/booking_detail_screen.dart';
part 'widgets/build_header.dart';
part 'widgets/build_coupon_booking.dart';
part 'widgets/build_apply_button.dart';
part 'widgets/build_coupon_success.dart';
part 'widgets/build_list_tile.dart';
part 'widgets/build_service_list.dart';
