name: barbershop_new
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.4.12+12

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  awesome_card: ^1.1.7
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_star: ^1.2.0
  flutter_svg: ^2.0.6
  flutter_swiper_null_safety: ^1.0.2
  fluttertoast: ^8.2.2
  get: ^4.6.5
  google_fonts: ^4.0.4
  intl: any
  launch_review: ^3.0.1
  octo_image: ^1.0.2
  pin_code_fields: ^7.4.0
  provider: ^6.0.5
  readmore: ^2.2.0
  share: ^2.0.4
  timeago: ^3.4.0
  url_launcher: ^6.1.11
  image_cropper: ^4.0.1
  image_picker: ^0.8.7+5
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
